ALTER TABLE account ADD COLUMN user_id UUID NOT NULL REFERENCES users(id);

ALTER TABLE category ADD COLUMN user_id UUID NOT NULL REFERENCES users(id);

ALTER TABLE transaction ADD COLUMN user_id UUID NOT NULL REFERENCES users(id);

ALTER TABLE budget ADD COLUMN user_id UUID NOT NULL REFERENCES users(id);
